window.__JOB_DATA__ = {
  "generatedAt": "2026-06-09 14:32:18",
  "totalJobs": 27,
  "totalNews": 10,
  "sourceCounts": [
    {
      "source": "IBPS",
      "count": 18
    },
    {
      "source": "NTA",
      "count": 9
    }
  ],
  "featuredJob": {
    "id": 38828,
    "title": "genadmin[at]nta[dot]ac[dot]in",
    "source": "NTA",
    "link": "Mailto:genadmin@nta.ac.in",
    "type": "Official Update",
    "tag": "nta",
    "scope": "NTA",
    "pdf": false,
    "description": "First Floor, NSIC-MDBP Building,Okhla Industrial Estate, New Delhi, Delhi 110020 011-69227700",
    "publishedLabel": "Updated 2026-06-09",
    "scrapedAt": "2026-06-09 14:31:43"
  },
  "resourceJobs": [
    {
      "id": 38827,
      "title": "NTA Registration and MoA",
      "source": "NTA",
      "link": "https://nta.ac.in/Download/NTARegistrationandMOA.pdf",
      "type": "PDF Notice",
      "tag": "nta",
      "scope": "NTA",
      "pdf": true,
      "description": "Mock Test Instagram Facebook Whatsapp Channel LinkedIn Youtube Twitter Play Store App Store",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:43"
    }
  ],
  "jobs": [
    {
      "id": 38828,
      "title": "genadmin[at]nta[dot]ac[dot]in",
      "source": "NTA",
      "link": "Mailto:genadmin@nta.ac.in",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "First Floor, NSIC-MDBP Building,Okhla Industrial Estate, New Delhi, Delhi 110020 011-69227700",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:43"
    },
    {
      "id": 38827,
      "title": "NTA Registration and MoA",
      "source": "NTA",
      "link": "https://nta.ac.in/Download/NTARegistrationandMOA.pdf",
      "type": "PDF Notice",
      "tag": "nta",
      "scope": "NTA",
      "pdf": true,
      "description": "Mock Test Instagram Facebook Whatsapp Channel LinkedIn Youtube Twitter Play Store App Store",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:43"
    },
    {
      "id": 38816,
      "title": "MOOCs Swayam Examination",
      "source": "NTA",
      "link": "https://nta.ac.in/Swayamexam",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Swayam JEE (Main) Engineering Joint Entrance Examination - (Main) NEET (UG) Medical National Eligibility Cum Entrance Test - (UG) CUET (UG) University Common University Entrance Test - (UG) UGC-NET University UGC National Eligibility Test CSIR NET University CSIR-National Eligibility Test (CSIR-NET)",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:43"
    },
    {
      "id": 38815,
      "title": "Engineering Joint Entrance Examination - (Main)",
      "source": "NTA",
      "link": "https://nta.ac.in/Engineeringexam",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Swayam MOOCs Swayam Examination JEE (Main) NEET (UG) Medical National Eligibility Cum Entrance Test - (UG) CUET (UG) University Common University Entrance Test - (UG) UGC-NET University UGC National Eligibility Test CSIR NET University CSIR-National Eligibility Test (CSIR-NET)",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:43"
    },
    {
      "id": 38814,
      "title": "Registration for observers of NTA is open. All eligible observer are requested to register themselves.",
      "source": "NTA",
      "link": "http://cbtc.nta.ac.in/observer",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Registration for observers of NTA is open. All eligible observer are requested to register themselves.",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:41"
    },
    {
      "id": 38813,
      "title": "CONTACT US",
      "source": "NTA",
      "link": "https://nta.ac.in/ContactUs",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "CONTACT US",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:39"
    },
    {
      "id": 38812,
      "title": "Hotel Management Joint Entrance Examination",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/nchm-jee/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Joint Entrance Examination Common Management Admission Test UGC National Eligibility Test ICAR'S All India Entrance Examination Study Web of Active learning by Young and Aspiring Minds",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:39"
    },
    {
      "id": 38811,
      "title": "ICAR'S All India Entrance Examination",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/icar/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Joint Entrance Examination Common Management Admission Test UGC National Eligibility Test Hotel Management Joint Entrance Examination Study Web of Active learning by Young and Aspiring Minds",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:39"
    },
    {
      "id": 38810,
      "title": "Joint Entrance Examination",
      "source": "NTA",
      "link": "https://jeemain.nta.nic.in",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Common Management Admission Test UGC National Eligibility Test ICAR'S All India Entrance Examination Hotel Management Study Web of Active learning by Young and Aspiring Minds",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:31:39"
    },
    {
      "id": 38804,
      "title": "CRP Specialist Officer",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/specialist-officers",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP Clerical cadre CRP PO/MT CRP RRB",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:34"
    },
    {
      "id": 38801,
      "title": "CRP RRB",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/regional-rural-bank",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP Clerical cadre CRP PO/MT CRP Specialist Officer",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:34"
    },
    {
      "id": 38805,
      "title": "Personnel Selection Services For Recruitment, Promotion And Placement",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/services",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "Personnel Selection Services for Recruitment, Promotion and Placement",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38803,
      "title": "CRP - PO/MTs",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/management-trainees",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "HOME RECRUITMENT EXAMS CRP - RRBs CRP - CLERKS CRP - SPECIALIST OFFICERS",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38802,
      "title": "CRP Clerical cadre",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/clerical-cadre",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP PO/MT CRP RRB CRP Specialist Officer",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38791,
      "title": "IEB Direct Recruitment Drive for Deputy Managers Registration From 26-May-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/iebddmapr26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "IEB Direct Recruitment Drive for Deputy Managers Registration From 26-May-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38790,
      "title": "BPCL Lateral Mid-Senior Level Recruitment Drive Registration From 31-May-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/bpcllmsmay26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "BPCL Lateral Mid-Senior Level Recruitment Drive Registration From 31-May-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38789,
      "title": "MPA Recruitment of Deputy Director (Class I Post) Registration From 05-June-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/mpaddapr26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "MPA Recruitment of Deputy Director (Class I Post) Registration From 05-June-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38788,
      "title": "RIICO Recruitment of Various post Registration From 06-Jun-2025",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/biprjan26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "RIICO Recruitment of Various post Registration From 06-Jun-2025",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38787,
      "title": "RIICO Recruitment of Junior Assistant & Junior Sales Assistant Registration From 06-Jun-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/rsicljan26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "RIICO Recruitment of Junior Assistant & Junior Sales Assistant Registration From 06-Jun-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38786,
      "title": "IPPBL Recruitment of Chief Operating Officer (COO) Registration From 01-May-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/ippblapr26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "IPPBL Recruitment of Chief Operating Officer (COO) Registration From 01-May-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38785,
      "title": "IEB Direct Recruitment Drive for Management Trainees Registration From 15-May-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/iebmtapr26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "IEB Direct Recruitment Drive for Management Trainees Registration From 15-May-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38784,
      "title": "OSWC Recruitment of Assistant Superintendent and Warehouse Assistant Registration From 15-May-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/oswcoct25/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "OSWC Recruitment of Assistant Superintendent and Warehouse Assistant Registration From 15-May-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38783,
      "title": "NALCO Recruitment of Non-Executive Personnel Registration From 21-May-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/nalconeapr26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "NALCO Recruitment of Non-Executive Personnel Registration From 21-May-2026",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38782,
      "title": "CRP Specialist Officers",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/specialist-officers/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP RRBs CRP CSA(Customer Service Associates) CRP PO/MTs Mock Test",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38781,
      "title": "CRP PO/MT",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/management-trainees/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP Clerical cadre CRP RRB CRP Specialist Officer",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38780,
      "title": "CRP CSA(Customer Service Associates)",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/clerical-cadre/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP RRBs CRP PO/MTs CRP Specialist Officers Mock Test",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    },
    {
      "id": 38779,
      "title": "CRP RRBs",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/regional-rural-bank/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP CSA(Customer Service Associates) CRP PO/MTs CRP Specialist Officers Mock Test",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:30:33"
    }
  ],
  "news": [
    {
      "id": 38838,
      "title": "BSEB Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/bihar-board-bseb-class-12th-intermediate-result",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: BSEB Class 12 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38837,
      "title": "ASSEB Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/assam-board-asseb-10th-result/129768562",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: ASSEB Class 10 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38836,
      "title": "UP Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/upmsp-up-board-class-10th-result/109005635",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: UP Class 10 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38835,
      "title": "UP Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/upmsp-up-board-class-12th-result/109005657",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: UP Class 12 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38834,
      "title": "Telangana SSC Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/telangana-board-ts-ssc-10th-class-result/129797969",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: Telangana SSC Class 10 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38833,
      "title": "CGBSE Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/chhattisgarh-cgbse-board-class-12th-result/120302476",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: CGBSE Class 12 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38832,
      "title": "CGBSE Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/chhattisgarh-cgbse-board-class-10th-result/120302481",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: CGBSE Class 10 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38831,
      "title": "AP Board Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/ap-board-bseap-class-10th-result/120300127",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: AP Board Class 10 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38830,
      "title": "WBCHSE Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/wb-board-12th-result/109398428",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: WBCHSE Class 12 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    },
    {
      "id": 38829,
      "title": "WBBSE Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/wb-board-10th-result/109398401",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: WBBSE Class 10 Result",
      "publishedLabel": "Updated 2026-06-09",
      "scrapedAt": "2026-06-09 14:32:18"
    }
  ]
};
