window.__JOB_DATA__ = {
  "generatedAt": "2026-10-01 20:44:19",
  "totalJobs": 32,
  "totalNews": 10,
  "sourceCounts": [
    {
      "source": "NTA",
      "count": 17
    },
    {
      "source": "IBPS",
      "count": 15
    }
  ],
  "featuredJob": {
    "id": 68765,
    "title": "genadmin[at]nta[dot]ac[dot]in",
    "source": "NTA",
    "link": "Mailto:genadmin@nta.ac.in",
    "type": "Official Update",
    "tag": "nta",
    "scope": "NTA",
    "pdf": false,
    "description": "National Testing Agency (NTA),5th Floor, Government of India Press Building Minto Road, New Delhi - 110002 011-69227700",
    "publishedLabel": "Updated 2026-10-01",
    "scrapedAt": "2026-10-01 20:44:18"
  },
  "resourceJobs": [
    {
      "id": 68764,
      "title": "NTA Registration and MoA",
      "source": "NTA",
      "link": "https://nta.ac.in/Download/NTARegistrationandMOA.pdf",
      "type": "PDF Notice",
      "tag": "nta",
      "scope": "NTA",
      "pdf": true,
      "description": "Mock Test Instagram Facebook Whatsapp Channel LinkedIn Youtube X Play Store App Store",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:18"
    },
    {
      "id": 68750,
      "title": "EXAM CALENDAR",
      "source": "NTA",
      "link": "https://nta.ac.in/Download/Notice/Examcalendar.pdf",
      "type": "PDF Notice",
      "tag": "nta",
      "scope": "NTA",
      "pdf": true,
      "description": "EXAM CALENDAR",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:09"
    },
    {
      "id": 68719,
      "title": "Updated Vacancies as on 29.09.2026 for Common Recruitment Process for CRP-CSA-XVI",
      "source": "IBPS",
      "link": "https://www.ibps.in/wp-content/uploads/Annexure_Corrigendum_29.09.2026.pdf",
      "type": "PDF Notice",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": true,
      "description": "CRP-CSA-XVI Posted on 29 Sep, 2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68717,
      "title": "Corrigendum dated 29.09.2026 in connection with CRP-CSA-XVI",
      "source": "IBPS",
      "link": "https://www.ibps.in/wp-content/uploads/Corrigendum-CRP-CSA_XVI_29.09.2026.pdf",
      "type": "PDF Notice",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": true,
      "description": "CRP-CSA-XVI Posted on 29 Sep, 2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    }
  ],
  "jobs": [
    {
      "id": 68765,
      "title": "genadmin[at]nta[dot]ac[dot]in",
      "source": "NTA",
      "link": "Mailto:genadmin@nta.ac.in",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "National Testing Agency (NTA),5th Floor, Government of India Press Building Minto Road, New Delhi - 110002 011-69227700",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:18"
    },
    {
      "id": 68764,
      "title": "NTA Registration and MoA",
      "source": "NTA",
      "link": "https://nta.ac.in/Download/NTARegistrationandMOA.pdf",
      "type": "PDF Notice",
      "tag": "nta",
      "scope": "NTA",
      "pdf": true,
      "description": "Mock Test Instagram Facebook Whatsapp Channel LinkedIn Youtube X Play Store App Store",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:18"
    },
    {
      "id": 68753,
      "title": "MOOCs Swayam Examination",
      "source": "NTA",
      "link": "https://nta.ac.in/Swayamexam",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Swayam JEE (Main) Engineering Joint Entrance Examination - (Main) NEET (UG) Medical National Eligibility Cum Entrance Test - (UG) CUET (UG) University Common University Entrance Test - (UG) UGC-NET University UGC National Eligibility Test CSIR NET University CSIR-National Eligibility Test (CSIR-NET)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:17"
    },
    {
      "id": 68752,
      "title": "Engineering Joint Entrance Examination - (Main)",
      "source": "NTA",
      "link": "https://nta.ac.in/Engineeringexam",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Swayam MOOCs Swayam Examination JEE (Main) NEET (UG) Medical National Eligibility Cum Entrance Test - (UG) CUET (UG) University Common University Entrance Test - (UG) UGC-NET University UGC National Eligibility Test CSIR NET University CSIR-National Eligibility Test (CSIR-NET)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:17"
    },
    {
      "id": 68751,
      "title": "Registration for observers of NTA is open. All eligible observer are requested to register themselves.",
      "source": "NTA",
      "link": "http://cbtc.nta.ac.in/observer",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Registration for observers of NTA is open. All eligible observer are requested to register themselves.",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:11"
    },
    {
      "id": 68750,
      "title": "EXAM CALENDAR",
      "source": "NTA",
      "link": "https://nta.ac.in/Download/Notice/Examcalendar.pdf",
      "type": "PDF Notice",
      "tag": "nta",
      "scope": "NTA",
      "pdf": true,
      "description": "EXAM CALENDAR",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:09"
    },
    {
      "id": 68749,
      "title": "CONTACT US",
      "source": "NTA",
      "link": "https://nta.ac.in/ContactUs",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "CONTACT US",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:09"
    },
    {
      "id": 68748,
      "title": "Rashtriya Indian Military College Entrance Examination (RIMCEE)",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/rimcee/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Rashtriya Indian Military College Entrance Examination (RIMCEE)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:09"
    },
    {
      "id": 68747,
      "title": "Hotel Management Joint Entrance Examination (NCHM-JEE)",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/nchm-jee/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Hotel Management Joint Entrance Examination (NCHM-JEE)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68746,
      "title": "National Institute of Fashion Technology Entrance Examination (NIFTEE)",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/niftee/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "National Institute of Fashion Technology Entrance Examination (NIFTEE)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68745,
      "title": "ICAR's All India Entrance Examination (ICAR-AIEEA/AICE-JRF/SRF-Ph.D.)",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/icar/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "ICAR's All India Entrance Examination (ICAR-AIEEA/AICE-JRF/SRF-Ph.D.)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68744,
      "title": "All India Sainik School Entrance Exam (AISSEE)",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/sainik-school-society/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "All India Sainik School Entrance Exam (AISSEE)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68743,
      "title": "Joint CSIR-UGC - National Eligibility Test (Joint CSIR-UGC NET)",
      "source": "NTA",
      "link": "https://csirnet.nta.nic.in/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Joint CSIR-UGC - National Eligibility Test (Joint CSIR-UGC NET)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68742,
      "title": "Common University Entrance Test-PG (CUET-PG)",
      "source": "NTA",
      "link": "https://exams.nta.nic.in/cuet-pg/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Common University Entrance Test-PG (CUET-PG)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68741,
      "title": "Common University Entrance Test-UG (CUET-UG)",
      "source": "NTA",
      "link": "https://cuet.nta.nic.in/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Common University Entrance Test-UG (CUET-UG)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68740,
      "title": "Joint Entrance Examination (JEE)",
      "source": "NTA",
      "link": "https://jeemain.nta.nic.in",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "Joint Entrance Examination (JEE)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68739,
      "title": "National Eligibility Cum Entrance Test (NEET)",
      "source": "NTA",
      "link": "https://neet.nta.nic.in/",
      "type": "Official Update",
      "tag": "nta",
      "scope": "NTA",
      "pdf": false,
      "description": "National Eligibility Cum Entrance Test (NEET)",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:08"
    },
    {
      "id": 68734,
      "title": "Personnel Selection Services For Recruitment, Promotion And Placement",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/services",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "Personnel Selection Services for Recruitment, Promotion and Placement",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68733,
      "title": "CRP Specialist Officer",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/specialist-officers",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP Clerical cadre CRP PO/MT CRP RRB",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68732,
      "title": "CRP - PO/MTs",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/management-trainees",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "HOME RECRUITMENT EXAMS CRP - RRBs CRP - CLERKS CRP - SPECIALIST OFFICERS",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68731,
      "title": "CRP Clerical cadre",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/clerical-cadre",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP PO/MT CRP RRB CRP Specialist Officer",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68730,
      "title": "CRP RRB",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/regional-rural-bank",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP Clerical cadre CRP PO/MT CRP Specialist Officer",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68722,
      "title": "MECL Recruitment of Non-Executive Posts Registration From 12-Sep-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/mecljul26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "MECL Recruitment of Non-Executive Posts Registration From 12-Sep-2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68721,
      "title": "IEB Special Recruitment Drive (SRD) Registration From 15-Sep-2026",
      "source": "IBPS",
      "link": "https://ibpsreg.ibps.in/iebsrdaug26/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "IEB Special Recruitment Drive (SRD) Registration From 15-Sep-2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68719,
      "title": "Updated Vacancies as on 29.09.2026 for Common Recruitment Process for CRP-CSA-XVI",
      "source": "IBPS",
      "link": "https://www.ibps.in/wp-content/uploads/Annexure_Corrigendum_29.09.2026.pdf",
      "type": "PDF Notice",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": true,
      "description": "CRP-CSA-XVI Posted on 29 Sep, 2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68717,
      "title": "Corrigendum dated 29.09.2026 in connection with CRP-CSA-XVI",
      "source": "IBPS",
      "link": "https://www.ibps.in/wp-content/uploads/Corrigendum-CRP-CSA_XVI_29.09.2026.pdf",
      "type": "PDF Notice",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": true,
      "description": "CRP-CSA-XVI Posted on 29 Sep, 2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68715,
      "title": "Provisional Allotment under Reserve List for CRP-RRBs\u2013XIV -Office Assistants (Multipurpose)",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/rural-bank-xiv/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP-RRBs\u2013XIV Posted on 30 Sep, 2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68713,
      "title": "Online Preliminary Exam Call Letter for CRP-CSA-XVI",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/clerical-cadre-xvi/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP-CSA-XVI Posted on 01 Oct, 2026",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68712,
      "title": "CRP Specialist Officers",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/specialist-officers/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP RRBs CRP CSA(Customer Service Associates) CRP PO/MTs Mock Test",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68711,
      "title": "CRP PO/MT",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/management-trainees/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP Clerical cadre CRP RRB CRP Specialist Officer",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68710,
      "title": "CRP CSA(Customer Service Associates)",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/clerical-cadre/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP RRBs CRP PO/MTs CRP Specialist Officers Mock Test",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    },
    {
      "id": 68709,
      "title": "CRP RRBs",
      "source": "IBPS",
      "link": "https://www.ibps.in/index.php/regional-rural-bank/",
      "type": "Official Update",
      "tag": "ibps",
      "scope": "IBPS",
      "pdf": false,
      "description": "CRP CSA(Customer Service Associates) CRP PO/MTs CRP Specialist Officers Mock Test",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:43:02"
    }
  ],
  "news": [
    {
      "id": 68775,
      "title": "BSEB Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/bihar-board-bseb-class-12th-intermediate-result",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: BSEB Class 12 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68774,
      "title": "ASSEB Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/assam-board-asseb-10th-result/129768562",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: ASSEB Class 10 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68773,
      "title": "UP Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/upmsp-up-board-class-10th-result/109005635",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: UP Class 10 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68772,
      "title": "UP Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/upmsp-up-board-class-12th-result/109005657",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: UP Class 12 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68771,
      "title": "Telangana SSC Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/telangana-board-ts-ssc-10th-class-result/129797969",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: Telangana SSC Class 10 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68770,
      "title": "CGBSE Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/chhattisgarh-cgbse-board-class-12th-result/120302476",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: CGBSE Class 12 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68769,
      "title": "CGBSE Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/chhattisgarh-cgbse-board-class-10th-result/120302481",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: CGBSE Class 10 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68768,
      "title": "AP Board Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/ap-board-bseap-class-10th-result/120300127",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: AP Board Class 10 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68767,
      "title": "WBCHSE Class 12 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/wb-board-12th-result/109398428",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: WBCHSE Class 12 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    },
    {
      "id": 68766,
      "title": "WBBSE Class 10 Result",
      "source": "TOI_NEWS",
      "link": "https://timesofindia.indiatimes.com/education/results/board-exam-results/wb-board-10th-result/109398401",
      "type": "Official Update",
      "tag": "toi_news",
      "scope": "TOI_NEWS",
      "pdf": false,
      "description": "Education news from Times of India: WBBSE Class 10 Result",
      "publishedLabel": "Updated 2026-10-01",
      "scrapedAt": "2026-10-01 20:44:19"
    }
  ]
};
